import {StyleSheet} from 'react-native'

const style = StyleSheet.create({
    container:{
        flex:1,
        flexDirection:'column'
    },
    header:{
        flex:0.2,
        flexDirection:'column'
    },
    topHeader:{
        flex:2,
        flexDirection:'row',
    },
    containerIconHeader:{
        flex:1
    },
    title:{
        flex:8,
        paddingTop:5
    },
    iconHeader:{
        height:40,
        width:40
    },
    centerHeader:{
        flex:3,
        flexDirection:'row',
    },
    content:{
        paddingBottom:20
    },
    containerIconMenu:{
        flex:1,
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'center'
    },
    containerMenu:{
        flex:1,
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'center'
    },
    iconMenu:{
        height:20,
        width:20,
    },
    backgroundMenuAktif:{
        backgroundColor:'#ddd',
        borderRadius:10,
        flex:1,
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'center'
    },
    topContent:{
        paddingLeft:10,
        paddingRight:10,
        borderBottomColor:'#ddd',
        borderBottomWidth:5,
        flex:1,
        paddingBottom:20,
    
    },
    centerContent:{
        paddingLeft:10,
        paddingRight:10,
        flex:1,
    },
    searchText:{
        marginLeft:-5,
        fontSize:20,
        fontWeight:'bold'
    },
    search:{
        marginTop:5
    },
    searchButton:{
        backgroundColor:'#ddd',
        height:30,
        borderRadius:20,
        flexDirection:'row',
        paddingTop:5,
        textDecorationColor:'#ccc'
    },
    textContent:{
        fontSize:18,
        fontWeight:'bold'
    },
    promo:{
        height:200,
        flex:1,
        marginTop:10
    },
    containerMenuLogin:{
        flex:1,
        backgroundColor:'#70dc65',
        flexDirection:'row',
        marginTop:10
    },
    leftMenuLogin:{
        flex:1,
        padding:5
    },
    rightMenuLogin:{
        flex:1,
        alignItems:'flex-end',
        padding:10
    },
    imagePopularCity:{
        marginTop:10,
        height:150,
        width:120,
        justifyContent:'flex-end',
        alignItems:'center',
        marginLeft:5,
        borderRadius:20
    },
    containerImagePopularcity:{
        flex:1,flexDirection:'row',
        borderRadius:20
    },
    slide: {
        width: 100,
        height: 100
        // other styles for your item's container
    }
})

export default style