
//   List RENTLIST Type
export const GET_RENTLIST = 'GET_RENTLIST'
export const GET_RENTLIST_FULFILLED = "GET_RENTLIST_FULFILLED"
export const GET_RENTLIST_REJECTED = "GET_RENTLIST_REJECTED"


//   List RENTLIST_TOWN Type 
export const GET_RENTLIST_TOWN = 'GET_RENTLIST_TOWN'
export const GET_RENTLIST_TOWN_FULFILLED = "GET_RENTLIST_TOWN_FULFILLED"
export const GET_RENTLIST_TOWN_REJECTED = "GET_RENTLIST_TOWN_REJECTED"


//   List RENTLIST_ID Type 
export const GET_RENTLIST_ID = 'GET_RENTLIST_ID'
export const GET_RENTLIST_ID_FULFILLED = "GET_RENTLIST_ID_FULFILLED"
export const GET_RENTLIST_ID_REJECTED = "GET_RENTLIST_ID_REJECTED"